# Generated by Django 5.2.4 on 2025-07-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name_plural": "Movies"},
        ),
    ]
